apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-seed
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ZivISM/advanced_argo_helm_test.git
    targetRevision: HEAD # Could be a branch, tag, or commit SHA
    path: /environments/dev/
  destination:
    server: https://kubernetes.default.svc # Cluster API server address
    namespace: myapp # Namespace where resources will be deployed
  syncPolicy:
    automated:
      prune: true # Automatically delete resources that are no longer in the Git repo
      selfHeal: true # Automatically sync resources if they drift from the Git repo
    syncOptions:
    - CreateNamespace=true # Automatically create namespace if it doesn't exist