apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name | default .Release.Name }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  selector:
    app: {{ .Release.Name }}
  ports:
    - port: {{ .Values.service.port | default 80 }}
      targetPort: 80
      protocol: TCP
      name: http
