replicaCount: 2

image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  name: myapp-service
  type: ClusterIP
  port: 80

ingress:
  enabled: false

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}

