global:
  environment:  
    source:
      repoURL: https://github.com/ZivISM/advanced_argo_helm_test.git
      targetRevision: HEAD 
      path: myapp
    destination:
      server: https://kubernetes.default.svc 
      namespace: myapp-dev-shlirabak
    syncPolicy:
      automated:
        prune: true 
        selfHeal: true 
    syncOptions:
    - CreateNamespace=true 
